name: Python application

on:
  push:
    branches: 
      - master
      - testing
      - feature
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check installer for errors
      run: |
        chmod +x install.sh
        ./install.sh
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_USERNAME: GitHub
        SLACK_ICON: https://www.stickpng.com/assets/images/5847f98fcef1014c0b5e48c0.png
        SLACK_TITLE: Push passed bug checking!
        SLACK_MESSAGE: 'The latest push to the clexography repo has been checked with pylint and is free of bugs! Your welcome! Beep...'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Failed Check - Slack
      if: failure()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_USERNAME: GitHub
        SLACK_COLOR: '#ff0000'
        SLACK_ICON: https://www.stickpng.com/assets/images/5847f98fcef1014c0b5e48c0.png
        SLACK_TITLE: Push didn't pass bug checking.
        SLACK_MESSAGE: 'The latest push to the clexography repo has been checked with pylint and it has some bugs that are in need of fixing. Sad beep...'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Discord Notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Triggered on: {{ EVENT_PAYLOAD.push.commits[][author][message] }} The latest push to the clexography repo has been checked with pylint and is free of bugs! Your welcome! Beep...'
    - name: Failed Check - Discord
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The latest push to the clexography repo has been checked with pylint and it has some bugs that are in need of fixing. Sad beep...'
